//fix bug: put address in the  environment file for this plugin

### Get all countries
#@insecure
GET {{Host}}/countries/
Accept: application/json

### Search for a country
#@insecure
GET {{Host}}/countries/unitedKimdom
Accept: application/json
